name: ISPUclassification
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  http: ^0.13.6
  intl: ^0.18.1
  syncfusion_flutter_charts: ^22.1.34

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ff0000"
  android_12:
    color: "#ff0000"

flutter:
  uses-material-design: true
